# -*- coding: utf-8 -*-
"""api_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15hVnhUkNe1x65NNNlBY3pPcSXVewpLBF
"""

from fastapi import FastAPI

api=FastAPI()

@api.get('/predict')
def marks(Enter_marks:int,Max_marks:int):
  percentage=(Enter_marks/Max_marks)*100
  if percentage<35:
    return{'Total_marks_scored': Enter_marks,
           'Percentage': percentage,
           'Grade': 'Fail'}
  elif percentage<=40:
    return{'Total_marks_scored':Enter_marks,
           'Percentage': percentage,
           'Grade': 'D'}
  elif percentage<=50:
    return{'Total_marks_scored':Enter_marks,
           'Percentage': percentage,
           'Grade': 'C'}
  elif percentage<=60:
    return{'Total_marks_scored':Enter_marks,
           'Percentage': percentage,
           'Grade': 'C+'}
  elif percentage<=70:
    return{'Total_marks_scored':Enter_marks,
           'Percentage': percentage,
           'Grade': 'B'}
  elif percentage<=80:
    return{'Total_marks_scored':Enter_marks,
           'Percentage': percentage,
           'Grade': 'B+'}
  elif percentage<=90:
    return{'Total_marks_scored':Enter_marks,
           'Percentage': percentage,
           'Grade': 'A'}
  else:
    return{'Total_marks_scored':Enter_marks,
           'Percentage': percentage,
           'Grade': 'A+'}

